import Link from "next/link";
import { ArrowLeft, CheckCircle2, Settings2 } from "lucide-react";
import s from "@/components/jobs/jobs.module.css";

export default function SetupPage() {
  return <main className={s.page}><div className={s.shell} style={{ maxWidth: 820 }}><nav className={s.nav}><Link href="/is"><ArrowLeft size={14} /> İş Fırsatları</Link></nav><header className={s.hero}><div><div className={s.eyebrow}>BİR KEZ KURALIM, SONRA TAKİPTE KALSIN</div><h1>İş Fırsatları kurulumu</h1><p className={s.muted}>Bu adımlar site yöneticisi içindir. Kurulumdan sonra ablan profilini site içinden doldurur.</p></div><Settings2 size={38} color="var(--accent)" /></header><div className={s.stack}>
    <Step number={1} title="Veritabanını hazırla"><p>Mevcut Supabase projesinin SQL Editor bölümünde <code>db/jobs.sql</code> dosyasını çalıştır. Yeni tablolar diğer uygulamalardan ayrıdır; tarayıcıdan doğrudan erişime kapalıdır.</p><p>Sunucuya <code>SUPABASE_SERVICE_ROLE_KEY</code> ekle. Bu anahtarı hiçbir zaman NEXT_PUBLIC_ değişkenine veya tarayıcıya koyma.</p></Step>
    <Step number={2} title="Özel alan ve AI bağlantısı"><p>Sunucuda güçlü, benzersiz bir <code>JOBS_PASSWORD</code> tanımla (en az 16 karakter önerilir). Var olan <code>SITE_GATE_SECRET</code> oturum imzalamak için kullanılır.</p><p>Mevcut <code>AI_BASE_URL</code>, <code>AI_API_KEY</code> ve <code>AI_MODEL</code> kullanılabilir. İstersen yalnızca iş değerlendirmesi için <code>JOBS_AI_MODEL</code> ekle.</p></Step>
    <Step number={3} title="İlan kaynaklarını bağla"><p><a href="https://tr.jooble.org/api/about" target="_blank" rel="noopener noreferrer" style={{ textDecoration: "underline" }}>Jooble Türkiye API</a> anahtarını <code>JOOBLE_API_KEY</code>, <a href="https://serpapi.com/google-jobs-api" target="_blank" rel="noopener noreferrer" style={{ textDecoration: "underline" }}>SerpApi</a> anahtarını <code>SERPAPI_API_KEY</code> olarak ekle. Kullanacağın kaynakların hesap ve kota koşullarını kontrol et.</p><p>Greenhouse ve Lever için API anahtarı gerekmez; takip edilecek şirketlerin kısa pano adları profil ekranına eklenir. Bu panolar yalnızca seçilen şirketleri kapsar. Bağlantısı olmayan kaynakları profilde kapat.</p></Step>
    <Step number={4} title="E-posta bildirimleri"><p><a href="https://resend.com/docs/dashboard/domains/introduction" target="_blank" rel="noopener noreferrer" style={{ textDecoration: "underline" }}>Resend</a> üzerinde gönderici alan adını doğrula. Sunucuya <code>RESEND_API_KEY</code> ve <code>JOBS_EMAIL_FROM=Ablam İş Fırsatları &lt;firsatlar@ablamablam.com&gt;</code> ekle. Adres kendi doğrulanmış alan adına ait olmalı.</p><p>Ablan profilindeki e-posta adresini kaydettikten sonra “Kayıtlı adrese test gönder” düğmesini kullan. Spam klasörünü de kontrol et.</p></Step>
    <Step number={5} title="7/24 zamanlayıcıyı çalıştır"><p>Rastgele uzun bir <code>CRON_SECRET</code> oluştur. Sunucu beş dakikada bir <code>GET /api/jobs/scan</code> isteğini <code>Authorization: Bearer CRON_SECRET</code> başlığıyla almalı.</p><p>Mevcut VPS üzerinde <code>JOBS_SITE_URL=https://ablamablam.com</code> ve aynı CRON_SECRET ile <code>npm run jobs:worker</code> çalıştır. Yeniden başlatmalardan sonra devam etmesi için <code>deploy/jobs-worker.service</code> systemd örneğini sunucunun dizinine göre düzenle.</p><p>Vercel kullanılıyorsa <code>deploy/vercel.jobs.example.json</code> içindeki cron ayarını proje yapılandırmasına birleştir. Hosting planının beş dakikalık cron ve 300 saniyelik fonksiyon süresini desteklediğini doğrula. Node zamanlayıcısı ile hosting cron&apos;undan yalnızca birini etkinleştir.</p></Step>
    <Step number={6} title="Profilini doldur ve ilk turu doğrula"><p>İş Fırsatları parolasıyla giriş yap. Mesleklerini, sektörlerini, becerilerini, konumunu ve ilgilerini gir; kaynakları seçip takibi aç. “Şimdi kontrol et” ilk turu başlatır. Sonraki turlar tarayıcı kapalıyken devam eder.</p><p>Kaynaklar ekranında gerçek bağlantı sonuçlarını; Sistem günlüğünde otomatik çalışma ve e-posta kayıtlarını kontrol et. Son 15 dakikada otomatik çalışma yoksa sistem uyarı gösterir.</p></Step>
    <div className={s.note}><CheckCircle2 size={18} style={{ marginBottom: 10 }} /><p>Varsayılan günlük sınırlar: 100 AI çağrısı ve 100 kaynak isteği. Bunlar para cinsinden harcama tavanı değildir; sağlayıcı hesaplarında da bütçe limiti tanımla. Her tur 5 ilan değerlendirilir; kalanlar sırada kalır. Kaynak başına tarama aralığı profilden ayarlanır.</p><p style={{ marginTop: 10 }}>Tüm interneti eksiksiz kapsama veya anında yakalama garantisi yoktur. Yayın tarihi olmayan veya yalnızca özeti alınan ilanlar açıkça gösterilir. Teknik ayrıntılar ve kurtarma adımları: <code>docs/JOBS_SETUP.md</code>.</p></div>
    <Link href="/is" className={`${s.button} ${s.primary}`}>İş Fırsatları&apos;na dön</Link>
  </div></div></main>;
}
function Step({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return <section className={s.panel}><h2 className={s.sectionTitle}><span className={s.badge}>{number}</span>{title}</h2><div className={s.muted} style={{ display: "flex", flexDirection: "column", gap: 12, overflowWrap: "anywhere" }}>{children}</div></section>;
}
